config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do #generates the 7 RESTful routes for products and do nested routes
    resources :reviews, only: [:show, :create, :destroy] #Nested routes allow you to capture an associative relationship in your routing
  end

  resources :users, only: [:new, :create] # for the users controller, only create the new and create routes
  resource :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new', as: :login

end

app/models/product.rb
class Product < ActiveRecord::Base
	# after_validation :format_name 
  has_many :reviews
  has_many :users, through: :reviews

	validates :description, :name, presence: true # a new Product can only be created if both description and the name values are present
  validates :price_in_cents, numericality: {only_integer: true} # a new Product can only be created if price_in_cents in only an integer 


  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product

	validates :user, presence: true
  validates :comment, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :reviews
	has_many :products, through: :reviews 

	has_secure_password #a library inherited from ActiveRecord
	# automatically add attr_accessor :password, :password_confirmation in your user model for you, which sets them up as virtual attributes (not database-backed) and special methods such as authenticate below
	# def authenticate
	# 	secret
	# end
	
	#validates :password, confirmation: true

	validates :name, :email, presence: true #validates user inputs a name when they create a user
	# validates :email, uniqueness: true, message: "That email exists" #validates the email is unique in the database
	# validate :name_starts_with_a
	# private
	# def name_starts_with_a
	# 	if first_name[0] != 'A'
	# 	errors.add(:first_name, "Doesn't start with A") # This shows a message 
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # Create a current_user helper method to show the log in status of the user
  # protected
  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id] #if the session of the user exists, assign the current_user to 

  	# if session[:user_id] This would call the database each time which is redundant
  	# 	User.find(session[:user_id])
  	# end
  end

#helper method works in views files
  helper_method :current_user

  #
  def ensure_logged_in
  	unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_sessions_path
  		# redirect_to products_url
  	end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.all
    end

    @products = @products.order(created_at: :desc).page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  	@product = Product.find(params[:id])
    @reviews = @product.reviews
    if current_user
      @review = @product.reviews.build
    end
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save #goes through validation process before saving
  		redirect_to products_url, notice: "Product successfully save!"
  	else
      flash.new[:alert] = "Error saving product"
  		render :new
  	end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	@product = Product.find(params[:id])
  	if @product.update_attributes(product_params)
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
  end

  private
  def product_params
  	#From params hash find the product key with a hash value and only retrieve the keys - name, description, price_in_cents
  	params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # before_action :ensure_logged_in  
  before_filter :ensure_logged_in, only: [:create, :destroy]
	before_filter :load_product
	# to run before every action, let's call a load_product method that retrieves the appropriate product so a new review can be associated to it

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	# @review = @product.reviews.build(review_params.merge(user: current_user))
    # @product = Product.find(params[:product_id])
  	@review = @product.reviews.build(review_params)
    @review.user = current_user
  	# What is actually happening in build:
  	# 	@review = Review.new(
    #   comment: params[:review][:comment],
    #   product_id: @product.id,
    #   user_id: current_user.id
    # )
    respond_to do |format|
  		if @review.save
        format.html { 
  			redirect_to products_path(@product), notice: "Review created successfully"
        }
        format.js {}
  		else
        format.html {
    			render "products/show",
          flash.new[:alert] = "Error creating product. Please try again."
        }
        format.js {}
    	end      
    end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private
  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  	# no need to instantiate a new object b/c only logging in, not creating a new user model/table
  end

  def create # Not creaitng a model. Instead, setting a hash in our users' browser to let our server (application) reference as they navigate through the application. Also not writing anything to the database so do not need a private method
  	user = User.find_by(email: params[:email]) # find a user by the email typed in and assign it to user variable
  	if user && user.authenticate(params[:password]) # check if user exists and it can be authenticated with the password typed in
  		session[:user_id] = user.id #Setting a cookie(a hash) by create key-value pair in session hash that lives in the browser, not in the rainforest server app
  		redirect_to products_url, notice: "Logged in!" #after session key is assigned, redirect the the products index page
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil #empty the session hash = unset the cookie
  	redirect_to products_url, notice: "Logged out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#instantiating a new user object
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signed up!" 
    else
      render "new", alert: "Please try again." #allows to pass along a msg to the next request
    end
  end

  private # private to not call the method anywhere else
  def user_params
    params.require(:user).permit(:email , :password, :password_confirmation, :name) #from the params hash, require the user key which has a value of a hash and only permit the keys email, password, and password_confirmation
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<!-- display notices or alerts whenever available. The application view is appropriate because we only have to write this code once and it can be reused across all views. 
If a notice key in the flash hash exists, display the value. If an alert key in the flash hash exists, display the value.
-->
  	<% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
  	<% end %>
  	<% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
  	<% end %>

    <nav>
      <%= link_to "Home", root_path %>
      <% if current_user %>
        Signed in as <%= current_user.name %> | <%= link_to "Log out", sessions_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_sessions_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </nav>
    
    <!-- yield to code from all other html files from the app -->
    <%= yield %> 

  </body>
  
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <!-- Display validations errors -->
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>

app/views/products/_product.html.erb
<li>
  <%= link_to product_path(product.id) do %>
    <h2>
      <%= number_to_currency(product.formatted_price) %>
      <%= product.name %>    
    </h2>
  <% end %>
  <!-- keeps the description to 100 characters or less -->
  <p><%= truncate(product.description, length: 100) %></p>
</li>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibit this review from being saved:</h2>
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <div class="alert">
          <li><%= msg %></li>
        </div>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_reviews.html.erb
<% if @product.reviews.count >= 1 %>
  <% @product.reviews.each do |review| %>
    <% unless review.new_record? %>
      <li class="review">
        <p class="comment">
          <%= review.comment %><br />
        </p>
        <% unless review.user.nil? %>
          <p class="poster">
            <em>Authored by <%= review.user.name %></em>
          Added on: <%= review.created_at %>
        <% end %>
      </li>
    <% end %>
  <% end %>
<% else %>
  <p>There are no reviews yet.</p> 
<% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<p>
	<%= link_to "Add a New Product ", "/products/new" %>
</p>

<!-- renders a helpful message with numbers of displayed vs. total entries -->
<p><%= page_entries_info @products %></p>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<div id="products">
	<ol>
  	<%= render @products %>
	</ol>
</div> 

<!-- outputs several pagination links such as « First ‹ Prev ... 2 3 4 5 6 7 8 9 10 ... Next › Last » -->
<p><%= paginate @products %></p>

app/views/products/index.js.erb
<% if params[:search] && params[:page].nil? %>
  $('#products').html("<%= j(render @products) %>");
<% else %>
  $('#products').append('<%= j render(@products) %>');
<% end %>

$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<h1>Add a New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product Information</h1>

<p>
<%= link_to "Back", products_path %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @product, method: :delete, data: {confirm: "Are you sure you want to delete this product?"}  %>
</p>

<div>
	<h2> <%= @product.name %>	</h2>

	<p> <%= @product.description %>	</p>

	<p>	Purchase for: $<%= @product.formatted_price %> </p>
</div>

<h3>Reviews for <%= @product.name %></h3>
<ul id="review-list">
	<%= render :partial => "reviews" %>
</ul>

<% if current_user %>
	<h4>Add a review</h4>
		<%= render 'reviews/form' %>
	<% else %>
	<p>Please <%= link_to "log in", new_sessions_path %> to add a review.</p>
<% end %>

<script type="text/javascript">
	$(function() {
		$("#new_review")
		.on('ajax:beforeSend', function() {
			$("input[type='submit']")
			.val('Saving...')
			.attr('disabled', 'disabled');
		})
		.on('ajax:complete', function() {
			$("input[type='submit']")
			.val('Create Review')
			.removeAttr('disabled');
		});
	});
</script>

app/views/products/show.js.erb
$('body').append("<%= escape_javascript(render @product) %>")

app/views/reviews/_form.html.erb
<%= form_for [@product, @review], :remote => true do |f| %>
	<div id="review-form-errors">
		<%= render :partial => "/products/review_form_errors" %>
	</div>

	<div class="field">
		<%= f.label :comment %><br/>
		<%= f.text_area :comment %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => 'products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => 'products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit <%= @review %></h1>

<%= render 'reviews/form' %>

<%= link_to 'Back', products_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>


<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions"><%= f.submit "Sign up" %></div>
<% end %>